### ISSUE TITLE
Setup automatic compilation on pull-requests

### ISSUE THREAD

**Issue by mlutfy** [ReseauLibre/commotion-router#2]
- Compile the code submitted on a pull-request (PR)
- Generate images and make them available for testing.

Aim: make it easy for people to send patches and test the resulting image.

**Comment by mlutfy** [comment]
Interesting post about how cmake works: http://www.kitware.com/blog/home/post/82

**Comment by mlutfy** [comment]
J'ai fait les changements suivants:
- Créer un utilisateur "symbiotic-ci" pour commenter dans les billets (quand un build réussi, échoue, etc). J'ai créé un groupe "Robots" sur l'organisation ReseauLibre de Github, et je lui ai donné un accès en écriture aux dépôts.
- Dans mon Jenkins (qui est dans le fond celui de SymbioTIC.coop), j'ai configuré une tâche "Reseaulibre Commotion" et j'ai commencé à y configurer le nécessaire pour lancer la construction.

Par contre, je n'ai pas encore terminé la configuration pour que ça compile comme il faut. Faudra aussi que ça puisse faire un scp des fichiers quelque part de public (ou bien utiliser les artefacts).

**Comment by elecnix** [comment]
Cool!

**Comment by mlutfy** [comment]
J'ai terminé la configuration dans Jenkins pour que ça "build" les images en utilisant le pull-request. Si le build fonctionne, les images sont archivées comme des artéfacts et poste l'URL dans un commentaire pour que l'on puisse accéder aux images.

Je considère que le gros du travail est terminé. On pourra ouvrir des billets séparés pour des points plus précis, s'il y en a.
